#!/usr/bin/env bash
# This script installs and configure HAProxy on lb-1 servece.

sudo apt-get -y update
sudo apt-get -y upgrade
sudo apt-get -y install haproxy
echo "ENABLED=1" | sudo tee -a /etc/default/haproxy
sudo cp /etc/haproxy/haproxy.cfg /etc/haproxy/haproxy.cfg.original
sudo sed -i "$ a\frontend web-frontend\n\tbind 0.0.0.0:80\n\tmode http\n\tdefault_backend web-backend\n\nbackend web-backend\n\tbalance roundrobin\n\tserver 201091-web-01 54.157.142.152:80 check\n\tserver 201091-web-02 34.201.161.176:80 check" /etc/haproxy/haproxy.cfg
sudo service haproxy start
