#!/usr/bin/env bash
# Create a script to install and configure HAProxy on lb-01 server
# Configure HAProxy to send traffic to web-01 and web-02 servers
# Distribute requests using a roundrobin algorithm
# Make sure that HAProxy can be managed via an init script

# Install and configure HAproxy on my lb-01 server.
sudo apt-get -y update
apt-get -y install haproxy

# configure haproxy
sudo vi /etc/haproxy/haproxy.cfg

# edit configuration file
"
frontend  proxynode
        bind *:80
        mode http
        default_backend web_backend
backend web_backend
        balance roundrobin
        server 201091-web-01 35.175.130.103:80 check
        server 201091-web-02 54.237.104.17:80 check
"

# enable haproxy via init script
sudo systemctl enable haproxy
sudo systemctl start haproxy

# check HAproxy configuration 
sudo haproxy -c -f /etc/haproxy/haproxy.cfg

# Restart HAProxy
sudo systemctl restart haproxy
